# Generated by Django 3.2 on 2022-03-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parts',
        ),
        migrations.AddField(
            model_name='product',
            name='parts',
            field=models.ManyToManyField(to='stock.Stock'),
        ),
        migrations.DeleteModel(
            name='Parts',
        ),
    ]
